version: '3.7'
services:
  vuecli:
    container_name: vuecli
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - '6600:8080'