version: '3.7'
services:
  vuecli:
    container_name: vuecli
#    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - '9999:8080'